# Generated by Django 3.1.7 on 2021-03-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name Planet')),
                ('satellites', models.SmallIntegerField()),
                ('diameter', models.FloatField()),
            ],
        ),
    ]
